# 应用服务 WEB 访问端口
server:
    port: 6000

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bishe?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
    profiles:
        active: dev
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER  # 解决Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
    redis:
        host: 127.0.0.1
        port: 6379
        password: 123456
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
            timeout: 30000
        database: 15

mybatis:
    configuration:
        map-underscore-to-camel-case: true

#mybatis-plus日志输入
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:**/dao/mapper/*.xml